# Generated by Django 5.2.13 on 2026-04-22 15:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepenseLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entreprise_id', models.PositiveIntegerField(db_index=True)),
                ('lot_id', models.BigIntegerField(db_index=True)),
                ('libelle', models.CharField(max_length=255)),
                ('montant', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('date_depense', models.DateTimeField(db_index=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_depense', '-id'],
                'indexes': [models.Index(fields=['entreprise_id', 'lot_id', 'date_depense'], name='lots_depens_entrepr_66407a_idx')],
            },
        ),
        migrations.CreateModel(
            name='LotStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entreprise_id', models.PositiveIntegerField(db_index=True)),
                ('article_id', models.CharField(db_index=True, max_length=32)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('quantite_entree', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=18)),
                ('quantite_restante', models.DecimalField(db_index=True, decimal_places=3, default=Decimal('0'), max_digits=18)),
                ('cout_unitaire_achat', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('date_entree', models.DateTimeField(db_index=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_entree', '-id'],
                'indexes': [models.Index(fields=['entreprise_id', 'article_id', 'date_entree'], name='lots_lotsto_entrepr_818e1f_idx')],
            },
        ),
    ]
