# Generated by Django 5.2.14 on 2026-05-15 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0003_lotstock_devise_depenselot_devise_lottransit_devise_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='lottransitarticle',
            new_name='lots_lottra_lot_tra_dbc149_idx',
            old_name='lots_lottra_lot_tra_cc915f_idx',
        ),
        migrations.RenameIndex(
            model_name='lottransitarticlefinancement',
            new_name='lots_lottra_lot_art_36d96e_idx',
            old_name='lots_lottra_lot_art_b1f033_idx',
        ),
        migrations.RenameIndex(
            model_name='lottransitfrais',
            new_name='lots_lottra_lot_tra_8c5361_idx',
            old_name='lots_lottra_lot_tra_c779ad_idx',
        ),
    ]
