# Generated by Django 5.2.13 on 2026-04-22 15:33

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('commande_id', models.CharField(editable=False, max_length=32, primary_key=True, serialize=False)),
                ('entreprise_id', models.PositiveIntegerField(db_index=True)),
                ('client_id', models.CharField(blank=True, db_index=True, max_length=32)),
                ('statut', models.CharField(choices=[('reservee', 'Réservée'), ('validee', 'Validée'), ('livree', 'Livrée'), ('annulee', 'Annulée')], db_index=True, default='reservee', max_length=20)),
                ('devise', models.CharField(default='USD', max_length=10)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('caisse_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('preuve_paiement', models.ImageField(blank=True, null=True, upload_to='commandes/preuves/')),
                ('note_client', models.CharField(blank=True, max_length=500)),
                ('date_commande', models.DateTimeField(db_index=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_commande', '-commande_id'],
                'indexes': [models.Index(fields=['entreprise_id', 'date_commande'], name='commandes_c_entrepr_04a604_idx'), models.Index(fields=['entreprise_id', 'client_id', 'date_commande'], name='commandes_c_entrepr_8225ad_idx')],
            },
        ),
        migrations.CreateModel(
            name='CommandeLigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commande_id', models.CharField(db_index=True, max_length=32)),
                ('article_id', models.CharField(db_index=True, max_length=32)),
                ('quantite', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=18)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('total_ligne', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['commande_id', 'article_id'], name='commandes_c_command_85c4a1_idx')],
            },
        ),
    ]
