# Generated by Django 5.2.13 on 2026-04-22 18:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='depot_montant',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18),
        ),
        migrations.AddField(
            model_name='commande',
            name='paiement_statut',
            field=models.CharField(choices=[('aucun', 'Aucun'), ('en_attente', 'En attente'), ('confirme', 'Confirmé'), ('refuse', 'Refusé')], db_index=True, default='aucun', max_length=20),
        ),
        migrations.CreateModel(
            name='ClientSoldeMouvement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entreprise_id', models.PositiveIntegerField(db_index=True)),
                ('client_id', models.CharField(db_index=True, max_length=32)),
                ('type', models.CharField(choices=[('credit', 'Crédit'), ('debit', 'Débit')], max_length=10)),
                ('montant', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('devise', models.CharField(default='USD', max_length=10)),
                ('date_mouvement', models.DateTimeField(db_index=True)),
                ('source_type', models.CharField(blank=True, max_length=30)),
                ('source_id', models.CharField(blank=True, max_length=64)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_mouvement', '-id'],
                'indexes': [models.Index(fields=['entreprise_id', 'client_id', 'date_mouvement'], name='commandes_c_entrepr_bbcff0_idx')],
            },
        ),
    ]
