# Generated by Django 5.2.14 on 2026-05-15 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0003_commande_en_attente_clientdettepaiement'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='clientdettepaiement',
            new_name='commandes_c_entrepr_540836_idx',
            old_name='commandes_c_entrepr_5bc032_idx',
        ),
        migrations.RenameIndex(
            model_name='clientdettepaiement',
            new_name='commandes_c_entrepr_e947a5_idx',
            old_name='commandes_c_entrepr_2579f9_idx',
        ),
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('reservee', 'Réservée'), ('validee', 'Validée'), ('livree', 'Livrée'), ('annulee', 'Annulée')], db_index=True, default='en_attente', max_length=20),
        ),
    ]
