# Generated by Django 5.2.13 on 2026-04-16 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffectEntreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=255, verbose_name='source')),
            ],
            options={
                'verbose_name': 'affectation entreprise',
                'verbose_name_plural': 'affectations entreprise',
            },
        ),
    ]
