# Generated by Django 5.2.13 on 2026-04-16 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_affect_entreprise'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super administrateur'), ('admin', 'Administrateur entreprise'), ('agent', 'Agent')], default='agent', help_text='superadmin : techniciens système (accès global). admin : propriétaire ou gestionnaire d’entreprise. agent : employé, droits limités.', max_length=20, verbose_name='rôle'),
        ),
    ]
