# Generated by Django 5.2.13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('secteur', models.CharField(max_length=255)),
                ('pays', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('nif', models.CharField(max_length=100, verbose_name='NIF')),
                ('responsable', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='entreprises/logos/')),
                (
                    'slogan',
                    models.CharField(
                        blank=True,
                        help_text="Devise ou slogan de l'entreprise (affiché dans l'en-tête des rapports)",
                        max_length=255,
                        null=True,
                    ),
                ),
            ],
            options={
                'verbose_name': 'entreprise',
                'verbose_name_plural': 'entreprises',
                'ordering': ['nom'],
            },
        ),
    ]
