# Generated by Django 5.2.13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_entreprise'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEntreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                (
                    'entreprise',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='membres_liens',
                        to='users.entreprise',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='entreprise_liens',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'affectation utilisateur — entreprise',
                'verbose_name_plural': 'affectations utilisateur — entreprise',
            },
        ),
        migrations.AddConstraint(
            model_name='userentreprise',
            constraint=models.UniqueConstraint(fields=('user', 'entreprise'), name='unique_user_entreprise'),
        ),
    ]
