# Generated by Django 5.2.13 on 2026-04-17 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_entreprise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'Un utilisateur avec ce nom existe déjà.'}, help_text='150 caractères maximum.', max_length=150, unique=True, verbose_name='nom d’utilisateur'),
        ),
    ]
