# Generated by Django 5.2.13 on 2026-04-17 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_nom_images_json'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='article',
            new_name='articles_ar_entrepr_e24361_idx',
            old_name='articles_art_entrep_nom_v2',
        ),
        migrations.AlterField(
            model_name='article',
            name='nom',
            field=models.CharField(max_length=500, verbose_name='nom'),
        ),
    ]
