# Generated by Django 5.2.14 on 2026-05-15 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_devise'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='devise',
            new_name='articles_de_entrepr_ef0746_idx',
            old_name='articles_de_entrepr_d1d402_idx',
        ),
    ]
