# Generated by Django 5.2.13 on 2026-04-22 15:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('vente_id', models.CharField(editable=False, max_length=32, primary_key=True, serialize=False)),
                ('entreprise_id', models.PositiveIntegerField(db_index=True)),
                ('client_nom', models.CharField(blank=True, max_length=255)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('devise', models.CharField(default='USD', max_length=10)),
                ('caisse_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('date_vente', models.DateTimeField(db_index=True)),
                ('created_by_user_id', models.CharField(blank=True, max_length=32)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_vente', '-vente_id'],
                'indexes': [models.Index(fields=['entreprise_id', 'date_vente'], name='ventes_vent_entrepr_3c1f4e_idx'), models.Index(fields=['entreprise_id', 'caisse_id', 'date_vente'], name='ventes_vent_entrepr_28c6df_idx')],
            },
        ),
        migrations.CreateModel(
            name='VenteFifoConsommation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vente_id', models.CharField(db_index=True, max_length=32)),
                ('vente_ligne_id', models.BigIntegerField(db_index=True)),
                ('lot_id', models.BigIntegerField(db_index=True)),
                ('article_id', models.CharField(db_index=True, max_length=32)),
                ('quantite', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=18)),
                ('cout_unitaire_achat', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('cout_unitaire_depenses', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['vente_id', 'article_id'], name='ventes_vent_vente_i_fb79b2_idx'), models.Index(fields=['lot_id'], name='ventes_vent_lot_id_a04a37_idx')],
            },
        ),
        migrations.CreateModel(
            name='VenteLigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vente_id', models.CharField(db_index=True, max_length=32)),
                ('article_id', models.CharField(db_index=True, max_length=32)),
                ('quantite', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=18)),
                ('prix_unitaire_vente', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('total_ligne', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['vente_id', 'article_id'], name='ventes_vent_vente_i_11cb0e_idx')],
            },
        ),
    ]
