# Generated by Django 5.2.13 on 2026-04-22 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='client_id',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AddField(
            model_name='vente',
            name='commande_id',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AddField(
            model_name='vente',
            name='type_vente',
            field=models.CharField(db_index=True, default='comptant', max_length=10),
        ),
    ]
