# Generated by Django 5.2.13 on 2026-04-22 15:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaisseCompte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entreprise_id', models.PositiveIntegerField(db_index=True)),
                ('nom', models.CharField(max_length=120)),
                ('actif', models.BooleanField(default=True)),
                ('created_by_user_id', models.CharField(blank=True, max_length=32)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_creation', '-id'],
                'indexes': [models.Index(fields=['entreprise_id', 'actif', 'nom'], name='caisse_cais_entrepr_1796c9_idx')],
            },
        ),
        migrations.CreateModel(
            name='MouvementCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entreprise_id', models.PositiveIntegerField(db_index=True)),
                ('caisse_id', models.BigIntegerField(db_index=True)),
                ('type', models.CharField(choices=[('entree', 'Entrée'), ('sortie', 'Sortie')], max_length=10)),
                ('montant', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('date_mouvement', models.DateTimeField(db_index=True)),
                ('libelle', models.CharField(blank=True, max_length=255)),
                ('source_type', models.CharField(blank=True, max_length=30)),
                ('source_id', models.CharField(blank=True, max_length=64)),
                ('created_by_user_id', models.CharField(blank=True, max_length=32)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_mouvement', '-id'],
                'indexes': [models.Index(fields=['entreprise_id', 'caisse_id', 'date_mouvement'], name='caisse_mouv_entrepr_e9b161_idx')],
            },
        ),
    ]
